stages:
  - build

build-job:
  stage: build
  script:
    - apk update && apk add --no-cache pkgconfig autoconf build-base binutils cmake curl file gcc g++ git libgcc libtool linux-headers make musl-dev ninja tar zip unzip wget
    - cd /tmp
    - git clone --branch v3.8 https://bitbucket.org/blaze-lib/blaze.git ./blaze
    - cmake -S "./blaze" -B "./blaze-build" -G Ninja -DCMAKE_BUILD_TYPE=Release -DUSE_LAPACK=Off
    - cmake --install "./blaze-build"
