---
title: "Drift report"
output: html_document
date: "`r format(Sys.time(), '%B %d, %Y')`"
fontsize: 12pt
params:
  input_params: NA
  step1_results_plot: NA
  step1_results_table: NA
  step2_results: NA
  step3_results: NA
  step4_results: NA
  step5_results: NA
---

## Table of Parameter values
```{r, echo = FALSE, warning = FALSE}
# Input parameter values
library(knitr)
# library(tidyr)
# params2 <- params$input_params %>% pivot_longer(names_to = "Parameters", values_to = "Value")
kable(params$input_params, caption = "")
#kable(params2, caption = "")
```

## Step 1: PSD Curve Fitting Results
```{r, echo = FALSE, warning = FALSE, comment=NA}
params$step1_results_plot
kable(params$step1_results_table)

```

## Step 2: Wet Bulb Calculation Results
```{r, echo = FALSE, warning = FALSE, comment=NA}
# tibble("Change in Wet Bulb Temperature (DTwb)" = round(params$step2_results[1],2),
#        "Wet Bulb Temperature (Twb)" = round(params$step2_results[2],2)
#        )
paste0("Change in Wet Bulb Temperature (DTwb): ", round(params$step2_results[1],2))
paste0("Wet Bulb Temperature (Twb): ", round(params$step2_results[2],2))

```

## Step 3: Wind Profile Calculation Results
```{r, echo = FALSE, warning = FALSE, comment=NA}
paste0("Friction height, cm (z0): ", round(params$step3_results[1],2))
paste0("Friction velocity, cm/sec (uf): ", round(params$step3_results[2],2))

```

## Step 4: Droplet Transport Calculation Results
```{r, echo = FALSE, warning = FALSE, comment=NA}
      
  ## Create Figure
      droplet1_data <- as_tibble(params$step4_results$droplet_1) %>%
        mutate(Droplet = "Centerline",
               ColorSet = "#ffd700")
      droplet2_data <- as_tibble(params$step4_results$droplet_2) %>%
        mutate(Droplet = "Downwind",
               ColorSet = "#00ffd7")
      droplet3_data <- as_tibble(params$step4_results$droplet_3) %>%
        mutate(Droplet = "Upwind",
               ColorSet = "#d700ff")
      
      All_droplet_data <- rbind(droplet1_data,
                                droplet2_data,
                                droplet3_data)
      
      Part4_plot <- ggplot(All_droplet_data, aes(x = Xdist, y = Dp.1.23., color = Droplet)) +
        geom_point(size = 3, alpha = 0.5) +
        scale_color_manual(values = c("#ffd700", "#00ffd7", "#d700ff")) +
        ylab("Initial Droplet Diameter (microns)") +
        xlab("Distance Traveled to Depositions from Nozzle Centerline (ft)") +
        theme_bw() +
        theme(
          legend.title = element_blank(),
          legend.background = element_rect(fill=alpha('white', 0.4)),
          legend.position = "right",
          legend.text = element_text(size = 16),
          axis.line = element_line(colour = "black"),
          axis.text.y = element_text(size = 16),
          axis.text.x = element_text(size = 16),
          axis.title.y = element_text(size = 16, vjust= 1.5),
          axis.title.x = element_text(size = 16)
        )    
    
      Part4_plot
      
      ## Print table of results
      All_droplet_data %>%
      select("Droplet_diameter" = "Dp.1.23.",
             "Distance_traveled" = "Xdist",
             Droplet) %>% 
        kable()
    
```

## Step 5: Deposition with Distance Calculations Results
```{r, echo = FALSE, warning = FALSE, comment=NA}
params$step5_results$dep_plot

tibble(Distance = params$step5_results$XX,
       Deposition = params$step5_results$APplume) %>%
  kable()

```
