---
title: "Run for multiple DSD Input with Common default Input parameters"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 7,
  fig.height = 6,
  echo=FALSE,
  warnings=FALSE,
  message = FALSE
)
```

```{r setup}
library(Casanova)
library(tidyverse)
library(nlstools)
library(nleqslv)
library(deSolve)
library(doParallel)
library(foreach)
library(ggplot2)
library(gridExtra)
```

## Read in DSD Data 

```{r naresh, eval=T}

library(dplyr)
library(plyr)
library(readxl)

# setwd("~/mondep/Casanova/")

data <- read_xlsx("~/mondep/Casanova/data-raw/2019 Sep 24 Bayer.xlsx","2019 Sep 24 Bayer") %>% filter(Solution != "Water")
treatments <- unique(data$Solution)
nozzles <- c("AI11004","SD11004","TTI11004","ULDM13004","UR11006")
dsd_bins <-c(18,22,26,30,36,44,52,62,74,86,100,120,150,180,210,250,300,360,410,500,600,720,860,1020,1220,1460,1740,2060,2460,2940,3500)
# for (treatment in treatments)
# {
#   for (nozzle in nozzles)
#   {
#     filename <- paste0("~/mondep/Casanova/vignettes/runBatch/Data/DSD_", treatment,"_",nozzle,".csv")
#     dsd <- data %>% filter(Solution == treatment & Nozzle == nozzle) %>% select(29:59)
#     dsd <- rbind(dsd_bins,dsd)
#     rownames(dsd) <- c("Droplet_Size_microns","Trial_1","Trial_2","Trial_3")
#     write.table(t(dsd),filename,sep=",",quote = F,row.names = F)
#     }
# }

getDSD <- function(data,dsd_bins=c(18,22,26,30,36,44,52,62,74,86,100,120,150,180,210,250,300,360,410,500,600,720,860,1020,1220,1460,1740,2060,2460,2940,3500),...){
  #
    dsd <- data %>% select(27:57)
    dsd <- rbind(dsd_bins,dsd)
    dsd <- t(dsd)
    colnames(dsd) <- c("Droplet_Size_microns","Trial_1","Trial_2","Trial_3")
    dsd <- dsd %>% as.data.frame
    return(dsd)
}

writeDSD <- function(dsd,dir="~/mondep/Casanova/vignettes/runBatch/Data/",nozzle,treatment){
  filename <- paste0(dir,"DSD_", treatment,"_",nozzle,".csv")
  write.table(dsd,filename,sep=",",quote = F,row.names = F)
}



tmp <- data %>% group_by(Solution,Nozzle) %>% nest() %>% filter(Solution=="Xtendimax" & Nozzle %in% c("SD11004","AI11004")) %>% mutate(dsd=map(data,getDSD)) %>% select(dsd)  %>% mutate(res=map(dsd,runCasanova)) 
```



```{r}
getdeposition <- function(resList){
  deposition <- resList$deposition
  tibble(Distance = deposition$XX,
       Deposition = deposition$APplume) 
}

tmp1 <- tmp%>% select(res) %>% mutate(depos=map(res,getdeposition)) %>% select(depos) %>% unnest(cols=c(depos))

ggplot(tmp1,aes(x=Distance,y=Deposition,col=Nozzle,lty=Solution))+ geom_point() + geom_line()+facet_grid(.~Nozzle)+scale_y_log10()+scale_x_log10()
```

