---
title: "Introduction"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 7,
  fig.height = 6
)
```

```{r setup}
library(Casanova)
library(tidyverse)
library(nlstools)
library(nleqslv)
library(deSolve)
library(doParallel)
library(foreach)
library(ggplot2)
library(gridExtra)
```

## Some Backgrounds

```{r}

```


## How-to

```{r}

```

## Reporting

## PART 1 PSD Curve Fitting

```{r}
# Curve fitting function
# Average DSD fit data:
y<-c( 0.000000,	0.000567,	0.002167,	0.005800,	0.011267,	0.018667,	0.031733,	0.053300,	0.086867,	0.128467,	0.194733,	0.291667,	0.421867,	0.581300,	0.759500,	0.933300,	0.999900,	1.000000)
y<-100*y
# Corresponding droplet size (in microns):
Dpdata<-c( 86, 100, 120, 150, 180, 210, 250, 300, 360, 410, 500, 600, 720, 860, 1020, 1220, 1460, 1740)
pars <- psd(y, Dpdata)
pars$plot
pars$table
```

### Part 2: Wet Bulb Calculation

```{r}
#  # User Input:
Tair<-17.689 # Dry air temperature, degrees C
Patm<-760 # Barometric pressure, mmHg abs
RH<-35.65  # Percent relative humidity

```


```{r}
Twb<- wet_bulb(Tair=17.689, Patm=760, RH=35.65)
Twb
# Change in Wet Bulb Temperature (DTwb in °C): 7.7
# Wet Bulb Temperature (Twb in °C): 9.99
```

### Part 3: Wind Profile Calculation

```{r}
  ch<-4 # crop height, inches
  z1<-6.6 # elevation of wind velocity in ft
  ux1<-12.8 # mph wind velocity at elevation
  # z1<-6.6
  # z2<-1.66667
  # ux1<-13.5
  # ux2<-9.44
```


```{r}
profile <- wvprofile(z1=10, ux1=12.8, ch=4)
# Friction height, cm (z0): 1.61
# Friction velocity, cm/sec (uf): 44.72
profile

z0<-profile[1]
Uf<-profile[2]
```

```{r}
WV2m (z1=10, z2=1.66667, ux1=12.8, ux2=9.44)
# Friction height, cm (z0): 0.33
# Friction velocity, cm/sec (uf): 33.53
```

### Part 4: Droplet Transport Calculation



```{r}
rhow<-1 # Density of pure water in droplet
rhos<-2.01594  # Density of dissolved solids in droplet, g/cc
xs0<-0.019369  # mass fraction total dissolved solids in solution

# Mix density (rows 25 to 42)
rhosoln<-1008.7 # in kg/m^3  # New input (need to be added to GUI)
# 
H0<-24 # Height of nozzle above ground , inches
hcm<-0 # Canopy height in cms
app_p<-63 # Nozzle pressure, psi

angle<-110 
p<-c(20,30,40,50,60,70,80)
NF<-c(0.28,0.35, 0.4,0.45, 0.49,0.53,0.57)

# ddd parameters
ddd1<-c(40,40,40,1.05,1.05,1.05,1.05,1.05,1.05,1.05,1.05,1.02,1.02,1.02,1.02,1.02,1.02,1.04,1.04,1.04,20,10,10)
ddd2<-c(40,40,40,1.05,1.05,1.05,1.05,1.05,1.05,1.05,1.05,1.02,1.02,1.02,1.02,1.02,1.02,1.04,1.04,1.04,20,10,10)
ddd3<-c(40,40,40,1.05,1.05,1.05,1.05,1.05,1.05,1.05,1.05,1.02,1.02,1.02,1.02,1.02,1.02,1.04,1.04,1.04,20,10,10)
```

```{r}
charac<-charact_cal(app_p,angle, rhosoln) 
charac
```


```{r}
DTwb<-Twb[1] # Wetbulb temperature depression, C
print("Solving Straight Down Problem")
droplet_1<-droplet_transport(Tair,RH,rhow,rhos,xs0,H0,DTwb,hcm,Uf,z0,app_p,charac[1],charac[2],ddd1,"Silent")
print("Solving with Wind Problem")
droplet_2<-droplet_transport(Tair,RH,rhow,rhos,xs0,H0,DTwb,hcm,Uf,z0,app_p,charac[3],charac[4],ddd2,"text")
print("Solving against Wind Problem")
droplet_3<-droplet_transport(Tair,RH,rhow,rhos,xs0,H0,DTwb,hcm,Uf,z0,app_p,charac[5],charac[6],ddd3,"Silent")

print("Finished Solving for Droplet Transport")

```

### Part 5: Deposition with Distance


```{r}
# User Inputs:
IAR<-0.4996 #Intended Application Rate for Dicamba, lb/acre
xactive<-0.003884 #Dicamba conc in tank solution, wtfraction
FD<-240.16 # Downwind field depth, ft
PL<-787.4 # Crosswind field width, ft
NozzleSpacing<-20 # Space between nozzles on Boom, inches
psipsipsi<-10.7 # Horizontal variation in wind direction around mean direction, 1 stdev, in degrees.
rhoL<-rhosoln/1000 # Density of sprayed solution, grams/cc
Dpmax<-1350
DDpmin<-18

# Integration input parameters
MMM<-500 # Original value
lambda<-3 # Original value; Controls resolution of deposition calculations; higher numbers increase accuracy

```

```{r}

# Part 5
# ________________________________________
a<-unname(pars$res)  # Calibration from step #1 (removing the stored names)

# Input from previous function
Cent<-droplet_1[2]$Xdist
Dwnd<-droplet_2[2]$Xdist
Uwnd<-droplet_3[2]$Xdist

deposition<-deposition_calcs(IAR,xactive,FD,PL, NozzleSpacing, psipsipsi,rhoL, Cent,Dwnd,Uwnd, Dpmax, DDpmin,a,MMM, lambda,"Silent")
deposition$dep_plot
###################
tibble(Distance = deposition$XX,
       Deposition = deposition$APplume) %>%
  knitr::kable()
```


### Part 6: Generate Report

```{r}

```


## Install the package

```{r}

```

