---
title: "Read in input for DRAW"
output: html_document
---

```{r}
library(tidyverse)
library(readxl)
```

## Some Backgrounds

- Tractor Speed (mph) = Field Length (ft)*Number of Nozzles on Boom*Flow per nozzle (gpm)/Volume Sprayed (gal)*60/5280

- VAR = Volume application rate
- IAR = Intended Application Rate of Dissolved Solids (DS), in lb/acre
- Boom Width = Field Depth

```{r}
dat <- readxl::read_excel(path = path.expand("~/SlimDrift/RawData/SETAC DRAW CDM Cases.xls"),sheet="Corrected DSD",n_max=53,skip=7,col_names = FALSE)
Rep <- as.numeric(dat$...3)

dat <- dat %>% mutate(Rep=as.numeric(...3)) %>% filter(!is.na(Rep)) %>% fill(...1) %>% fill(...2)
nms <- read_excel(path = path.expand("~/SlimDrift/RawData/SETAC DRAW CDM Cases.xls"),sheet="Corrected DSD",range="B5:AI6",col_names = F)
nms <- unlist(c(nms[2,1:3],nms[1,4:ncol(nms)]))
names(dat)[1:34] <- nms

```


```{r}
DSDTab <- readxl::read_excel(path = path.expand("~/SlimDrift/RawData/SETAC DRAW CDM Cases.xls"),sheet="DSD Data",range="B2:F9",col_names = TRUE)
DSDTab <- DSDTab[-1,]
```

```{r}
tmp <- left_join(dat,DSDTab) ### All DSD Data. 

## Note for that For AXI 11002, distance up to 600, whereas for others , up to 860.


```



```{r}
CDMinputs <- readxl::read_excel(path = path.expand("~/SlimDrift/RawData/SETAC DRAW CDM Cases.xls"),sheet="Reqd CDM Inputs",range = "B12:AV24",col_names = FALSE)
nms <- readxl::read_excel(path = path.expand("~/SlimDrift/RawData/SETAC DRAW CDM Cases.xls"),sheet="Reqd CDM Inputs",range = "B9:AV10",col_names = FALSE)
nms <-nms[c(2,1),]
nms <- gsub("NA.","",apply(nms,2,function(x){paste0(x,collapse = ".")}))
nms <- gsub(".NA","",nms)
nms <- gsub('\"',"",nms)
names(nms) <- NULL
nms
```

