---
title: "User Guide"
output:
  html_document: default
  pdf_document: default
---
<style type="text/css">

body{ /* Normal  */
      font-size: 14px;
  }
td {  /* Table  */
  font-size: 10px;
}
.title {
  font-size: 50px;
  color: #2196F3;
}
h1 { /* Header 1 */
  font-size: 40px;
}
h2 { /* Header 2 */
    font-size: 30px;
}
h3 { /* Header 3 */
  font-size: 25px;
  color: #1565C0;
}
.r{ /* Code block */
    font-size: 12px;
}
pre { /* Code block - determines code spacing between lines */
    font-size: 14px;
}
</style>
# User Guide  
This website provides an interactive tool to .... 

### Background
...

### Drift Model
- **Subsection**  

- **Subsection**  

### Data Description
... 

- **Subsection**  
...

***  

# Data Input  
This tab provides user controls data selection. ... 

### Upload
...

### Manual Entry
...

***

# Calculate
This tab runs all calculations. ... 

***

# Output
This tab displays all results. ... 

### Subsection ...

***

# Advanced
This tab allows users to access advanced features. ... 

### Subsection ...

***

# References  
...
  
R Core Team (2020). R: A language and environment for statistical computing. R Foundation for Statistical Computing, Vienna, Austria. <https://www.R-project.org/>  
  
Winston Chang, Joe Cheng, JJ Allaire, Yihui Xie and Jonathan McPherson (2020). shiny: Web Application Framework for R. R package version 1.4.0.2. <https://CRAN.R-project.org/package=shiny>  