---
title: "Casanova Drift report"
output: html_document
date: "`r format(Sys.time(), '%B %d, %Y')`"
fontsize: 12pt
params:
  input_scenarioID: NA
  input_filename: NA
  input_params: NA
  input_paramsWT: NA
  step1_results_plot: NA
  step1_results_table: NA
  step1_results_stats: NA
  step2_results: NA
  step3_results: NAs
  step4_results: NA
  step5_results: NA
---

## Scenario
```{r, echo = FALSE, warning = FALSE}
# Input parameter values
cat(as.character(params$input_scenarioID))
```

## Table of Parameter values
```{r, echo = FALSE, warning = FALSE}
# Input parameter values
kable(params$input_params, caption = "")
```

## Table of wind velocity and height measurements
```{r, echo = FALSE, warning = FALSE}
# Input parameter values
kable(params$input_paramsWT, caption = "")
```

## PSD Inputs
```{r, echo = FALSE, warning = FALSE, comment=NA}
params$step1_results_stats$plot
kable(params$step1_results_stats$stats)

```

## Step 1: PSD Curve Fitting Results
```{r, echo = FALSE, warning = FALSE, comment=NA, results = 'asis'}
params$step1_results_plot
kable(params$step1_results_table)

```

## Step 2: Wet Bulb Calculation Results
```{r, echo = FALSE, warning = FALSE, comment=NA}
cat(paste0("Change in Wet Bulb Temperature (DTwb): ", round(params$step2_results[1],2),"\nWet Bulb Temperature (Twb): ", round(params$step2_results[2],2)))

```

## Step 3: Wind Profile Calculation Results
```{r, echo = FALSE, warning = FALSE, comment=NA}
cat(paste0("Friction height, cm (z0): ", round(params$step3_results[1],2), "\nFriction velocity, cm/sec (uf): ", round(params$step3_results[2],2)))

```

## Step 4: Droplet Transport Calculation Results
```{r, echo = FALSE, warning = FALSE, comment=NA}
      
  ## Create Figure
      All_droplet_data <- params$step4_results

      Part4_plot <- plot_droplet_data(All_droplet_data)

      Part4_plot

      ## Print table of results
      All_droplet_data %>%
      select("Droplet_diameter" = "Droplet_diameter",
             "Distance_traveled" = "Distance_traveled",
             Droplet) %>%
        kable()
    
```

## Step 5: Deposition with Distance Calculations Results
```{r, echo = FALSE, warning = FALSE, comment=NA}
params$step5_results$dep_plot

tibble(Distance = params$step5_results$XX,
       Deposition = params$step5_results$APplume) %>%
  kable()

```
