---
title: "Laplace Distribution"
author: "Zhenglei Gao"
date: "8/11/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
loc <- 1; b <- 2
y <- rlaplace(n = 100, loc = loc, scale = b)
mean(y)  # sample mean
loc      # population mean
var(y)   # sample variance
2 * b^2  # population variance

## Not run:  
loc <- 0; b <- 1.5; x <- seq(-5, 5, by = 0.01)
plot(x, dlaplace(x, loc, b), type = "l", col = "blue", ylim = c(0,1),
     main = "Blue is density, orange is cumulative distribution function",
     sub = "Purple are 5,10,...,95 percentiles", las = 1, ylab = "")
abline(h = 0, col = "blue", lty = 2)
lines(qlaplace(seq(0.05,0.95,by = 0.05), loc, b),
      dlaplace(qlaplace(seq(0.05, 0.95, by = 0.05), loc, b), loc, b),
      col = "purple", lty = 3, type = "h")
lines(x, plaplace(x, loc, b), type = "l", col = "orange")
abline(h = 0, lty = 2) 
## End(Not run)

plaplace(qlaplace(seq(0.05, 0.95, by = 0.05), loc, b), loc, b)

```



```{r}
loc <- log(80); b <- 0.0001; x <- log(seq(1, 160, by = 1))
plot(exp(x), dlaplace(x, loc, b,log=F), type = "l", col = "blue", 
     main = "Blue is density, orange is cumulative distribution function",
     sub = "Purple are 5,10,...,95 percentiles", las = 1, ylab = "")
abline(h = 0, col = "blue", lty = 2)

plot(exp(x), plaplace(x, loc, b), type = "l", col = "orange")
abline(h = 0, lty = 2) 
```


```{r}
loc <- log(80); b <- 0.0001; x <- log(seq(1, 160, by = 1))
plot(exp(x), dnorm(x, loc, b,log=F), type = "l", col = "blue", 
     main = "Blue is density, orange is cumulative distribution function",
     sub = "Purple are 5,10,...,95 percentiles", las = 1, ylab = "")
abline(h = 0, col = "blue", lty = 2)

plot(exp(x), plaplace(x, loc, b), type = "l", col = "orange")
abline(h = 0, lty = 2) 

plaplace(qlaplace(seq(0.05, 0.95, by = 0.05), loc, b), loc, b)


```



```{r}
y <- rnorm(1000,loc, b)
plot(density(exp(y)),from=70,to=90)
```

